[tool.poetry]
name = "odooaiorpc"
version = "0.1.0"
description = ""
authors = ["Remy Zulauff <remy.zulauff@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
